### ISSUE TITLE
Golf 4 controller did not wake up when trying to get SKC

### ISSUE THREAD

**Issue by kai481** [gmenounos/kw1281test#102]
KW1281Test: Yesterday's diagnostics...Today.

Version 0.99.3-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM2 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.22631.0
.NET Version: 8.0.11
Culture: en-US
Opening serial port COM2
Sending wakeup message
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Caught: System.InvalidOperationException Controller did not wake up.
Unhandled exception: System.InvalidOperationException: Controller did not wake up.
   at BitFab.KW1281Test.KwpCommon.WakeUp(Byte, Boolean) in /Users/gmenounos/src/kw1281test/KwpCommon.cs:line 62
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in /Users/gmenounos/src/kw1281test/Tester.cs:line 31
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Tester.cs:line 505
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 277
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 33

I tried with 25(imobalizer) and with engine on and ignition on but can't manage to make it to connect to the module, the vcds works.
I have a hex v2 with atmega 162 chip
The car is a golf 4 from 1998 and I want to repair the imobalizer cause when I moved the chip and motherboard to a new key, the old one was falling appart, now my car wouldn't unlock with they radio key and windows will not work, interior lights, and maybe more(not found yet)
Hopefully you can help me get the SKC since vag eeprom programmer wouldn't find my ecu

**Comment by kai481** [comment]
[KW1281Test.log](https://github.com/user-attachments/files/18096435/KW1281Test.log)
I forgot about this one

**Comment by gmenounos** [comment]
Unfortunately the Hex V2 cable won't work because it doesn't support the Virtual COM Port drivers. You would need an older VCDS cable or a generic KKL cable: https://github.com/gmenounos/kw1281test/wiki#obdii-cable

Are you in the US? I ask because in the US, VW didn't use an immobilizer in the Golf 4 until model year 2000.

**Comment by kai481** [comment]
I live in EU and the car was made in Slovakia. I will buy an kkl cable

**Comment by kai481** [comment]
does the chip from kkl matter?

**Comment by kerekt** [comment]
For radio remote matching  you dont need login, radio remotes (plips)  stored usually in comfort modul 46

**Comment by AdvTechTS** [comment]
I have the same issue while trying to use a genuine Ross-Tech HEX+CAN. Vehicle is a 2003 Mk4 Golf. I have one original key that I accidently stuffed up the immobilizer coding trying to code a new non-genuine key with Autel KM100. I now need to reprogram both keys but require the SKC.

**Comment by AdvTechTS** [comment]
Here is my initial attempt:

`Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

C:\Users\User>cd desktop

C:\Users\User\Desktop>cd kw1281test

C:\Users\User\Desktop\kw1281test>KW1281Test COM2 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.99.3-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM2 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 8.0.11
Culture: en-AU
Opening serial port COM2
Sending wakeup message
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Caught: System.InvalidOperationException Controller did not wake up.
Unhandled exception: System.InvalidOperationException: Controller did not wake up.
   at BitFab.KW1281Test.KwpCommon.WakeUp(Byte, Boolean) in /Users/gmenounos/src/kw1281test/KwpCommon.cs:line 62
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in /Users/gmenounos/src/kw1281test/Tester.cs:line 31
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Tester.cs:line 505
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 277
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 33

`

**Comment by AdvTechTS** [comment]
Then tried changing the Baud to 9600, similar result:

C:\Users\User\Desktop\kw1281test>KW1281Test COM2 9600 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.99.3-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM2 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 8.0.11
Culture: en-AU
Opening serial port COM2
Sending wakeup message
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Caught: System.InvalidOperationException Controller did not wake up.
Unhandled exception: System.InvalidOperationException: Controller did not wake up.
   at BitFab.KW1281Test.KwpCommon.WakeUp(Byte, Boolean) in /Users/gmenounos/src/kw1281test/KwpCommon.cs:line 62
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in /Users/gmenounos/src/kw1281test/Tester.cs:line 31
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Tester.cs:line 505
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 277
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 33

**Comment by AdvTechTS** [comment]
When I tried without the Baud I got a Command List:

C:\Users\User\Desktop\kw1281test>KW1281Test COM2 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.99.3-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM2 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 8.0.11
Culture: en-AU
Usage: KW1281Test PORT BAUD ADDRESS COMMAND [args]
    PORT = COM1|COM2|etc.
    BAUD = 10400|9600|etc.
    ADDRESS = The controller address, e.g. 1 (ECU), 17 (cluster), 46 (CCM), 56 (radio)
    COMMAND =
        ActuatorTest
        AdaptationRead CHANNEL [LOGIN]
            CHANNEL = Channel number (0-99)
            LOGIN = Optional login (0-65535)
        AdaptationSave CHANNEL VALUE [LOGIN]
            CHANNEL = Channel number (0-99)
            VALUE = Channel value (0-65535)
            LOGIN = Optional login (0-65535)
        AdaptationTest CHANNEL VALUE [LOGIN]
            CHANNEL = Channel number (0-99)
            VALUE = Channel value (0-65535)
            LOGIN = Optional login (0-65535)
        BasicSetting GROUP
            GROUP = Group number (0-255)
            (Group 0: Raw controller data)
        ClarionVWPremium4SafeCode
        ClearFaultCodes
        DelcoVWPremium5SafeCode
        DumpEdc15Eeprom [FILENAME]
            FILENAME = Optional filename
        DumpEeprom START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 0) or hex (e.g. $0)
            LENGTH = Number of bytes in decimal (e.g. 2048) or hex (e.g. $800)
            FILENAME = Optional filename
        DumpMarelliMem START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 3072) or hex (e.g. $C00)
            LENGTH = Number of bytes in decimal (e.g. 1024) or hex (e.g. $400)
            FILENAME = Optional filename
        DumpMem START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 8192) or hex (e.g. $2000)
            LENGTH = Number of bytes in decimal (e.g. 65536) or hex (e.g. $10000)
            FILENAME = Optional filename
        DumpRam START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 8192) or hex (e.g. $2000)
            LENGTH = Number of bytes in decimal (e.g. 65536) or hex (e.g. $10000)
            FILENAME = Optional filename
        DumpRBxMem START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 66560) or hex (e.g. $10400)
            LENGTH = Number of bytes in decimal (e.g. 1024) or hex (e.g. $400)
            FILENAME = Optional filename
        FindLogins LOGIN
            LOGIN = Known good login (0-65535)
        GetSKC
        GroupRead GROUP
            GROUP = Group number (0-255)
            (Group 0: Raw controller data)
        LoadEeprom START FILENAME
            START = Start address in decimal (e.g. 0) or hex (e.g. $0)
            FILENAME = Name of file containing binary data to load into EEPROM
        MapEeprom
        ReadFaultCodes
        ReadIdent
        ReadEeprom ADDRESS
            ADDRESS = Address in decimal (e.g. 4361) or hex (e.g. $1109)
        ReadRAM ADDRESS
            ADDRESS = Address in decimal (e.g. 4361) or hex (e.g. $1109)
        ReadROM ADDRESS
            ADDRESS = Address in decimal (e.g. 4361) or hex (e.g. $1109)
        ReadSoftwareVersion
        Reset
        SetSoftwareCoding CODING WORKSHOP
            CODING = Software coding in decimal (e.g. 4361) or hex (e.g. $1109)
            WORKSHOP = Workshop code in decimal (e.g. 4361) or hex (e.g. $1109)
        ToggleRB4Mode
        WriteEdc15Eeprom ADDRESS1 VALUE1 [ADDRESS2 VALUE2 ... ADDRESSn VALUEn]
            ADDRESS = EEPROM address in decimal (0-511) or hex ($00-$1FF)
            VALUE = Value to be stored at address in decimal (0-255) or hex ($00-$FF)
        WriteEeprom ADDRESS VALUE
            ADDRESS = Address in decimal (e.g. 4361) or hex (e.g. $1109)
            VALUE = Value in decimal (e.g. 138) or hex (e.g. $8A)

**Comment by AdvTechTS** [comment]
Here is my Cluster Data and COM port settings
![Screenshot (27)](https://github.com/user-attachments/assets/3e67d968-0e71-4fe5-82b3-8d3a078bdb5b)
![Screenshot (30)](https://github.com/user-attachments/assets/2fc1118f-d374-430b-9a18-27efd9c9573f)
![Screenshot (31)](https://github.com/user-attachments/assets/b60c6829-a519-45df-b5db-4ff931b3a9a2)
![Screenshot (32)](https://github.com/user-attachments/assets/0d9e2edc-92e5-47f3-9f35-3cc6f95295ac)
![Screenshot (33)](https://github.com/user-attachments/assets/d545f69d-7b7a-466b-8916-2354c36eaca2)

**Comment by gmenounos** [comment]
In VCDS, make sure that "Boot in intelligent mode" is unchecked. Might have to unplug the cable after changing that setting.

**Comment by AdvTechTS** [comment]
Thanks @gmenounos I did as you said and it didn't work on it's own, but I had read in the forum that some had success with clicking restore defaults in the Serial Port Properties. So I did that. At the same time I went into Startup Apps and unchecked VCDS and then restarted the tablet and went into Task Manager to make sure VCDS wasn't running (it wasn't). Reloaded the Command Prompt and voila, success! :)

**Comment by kerekt** [comment]
for best result Usb virtual comports with Ftdi Chipet , always set Latency to 0 !!!!

![Latency0](https://github.com/user-attachments/assets/dca05fed-a3ec-4d6d-a249-34aada333edd)

**Comment by AdvTechTS** [comment]
I'll try the window with remote mod next ;)
