### ISSUE TITLE
InvalidOperationException when pairing fob; 2000 mk4 jetta

### ISSUE THREAD

**Issue by arrrobase** [gmenounos/kw1281test#16]
I successfully paired 3 keys after retrieving my skc. When attempting to add a fob following the [instructions](https://forums.tdiclub.com/index.php?threads/free-vds-pro-vagtacho-alternative.509151/page-25#post-5680848) on the forum, I encountered an error. I tried multiple times and kept getting the same error. During the first step a `NAK` was received.

```
C:\Users\mexan\Downloads\kw1281test_0.74-beta_Win10>kw1281test.exe com1 9600 46 AdaptationSave 0 0
KW1281Test: Yesterday's diagnostics...Today.

Version 0.74-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com1 9600 46 AdaptationSave 0 0
OSVersion: Microsoft Windows NT 10.0.19044.0
.NET Version: 6.0.2
Culture: en-US
Opening serial port com1
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0959799AJ 61 Zentral-SG Komf. 0001
Software Coding 04096, Workshop Code: 00066
Sending AdaptationRead block
Received a NAK.
Sending EndCommunication block

C:\Users\mexan\Downloads\kw1281test_0.74-beta_Win10>kw1281test.exe com1 9600 46 AdaptationSave 1 1
KW1281Test: Yesterday's diagnostics...Today.

Version 0.74-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com1 9600 46 AdaptationSave 1 1
OSVersion: Microsoft Windows NT 10.0.19044.0
.NET Version: 6.0.2
Culture: en-US
Opening serial port com1
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
Caught: System.InvalidOperationException Wrote 0xAA to port but echo was 0x01
Unhandled exception: System.InvalidOperationException: Wrote 0xAA to port but echo was 0x01
   at BitFab.KW1281Test.KwpCommon.WriteByteAndDiscardEcho(Byte b) in C:\Users\gmeno\src\kw1281test\KwpCommon.cs:line 200
   at BitFab.KW1281Test.KwpCommon.WriteByte(Byte b) in C:\Users\gmeno\src\kw1281test\KwpCommon.cs:line 108
   at BitFab.KW1281Test.KW1281Dialog.ReadAndAckByte() in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 401
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlock() in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 330
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlocks() in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 308
   at BitFab.KW1281Test.KW1281Dialog.Connect() in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 80
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean evenParityWakeup) in C:\Users\gmeno\src\kw1281test\Tester.cs:line 38
   at BitFab.KW1281Test.Program.Run(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 249
   at BitFab.KW1281Test.Program.Main(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 26
```

**Comment by arrrobase** [comment]
In case it helps, here's the ECU ident:

```
C:\Users\mexan\Downloads\kw1281test_0.74-beta_Win10>kw1281test.exe com1 10400 1 ReadIdent
KW1281Test: Yesterday's diagnostics...Today.

Version 0.74-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com1 10400 1 ReadIdent
OSVersion: Microsoft Windows NT 10.0.19044.0
.NET Version: 6.0.2
Culture: en-US
Opening serial port com1
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 021906018M  MOTRONIC ME7.1  G   6760
Software Coding 00031, Workshop Code: 23069
Sending ReadIdent block
Ident: 021906018M  MOTRONIC ME7.1  G   6760
Software Coding 00031, Workshop Code: 23069
Sending EndCommunication block
```

**Comment by gmenounos** [comment]
I'm not sure what went wrong with the adaptation save. I'll try this on my own car and see if it works or not.

**Comment by arrrobase** [comment]
I know this is old, but were you able to replicate the issue on your end?

**Comment by k7saru** [comment]
I’m also encountering this error with my 2004 Audi A4. The sync byte is unexpected and it fails
