### ISSUE TITLE
GetSKC Beetle cluster

### ISSUE THREAD

**Issue by fktbnd** [gmenounos/kw1281test#18]
Hello!

I have tried the getSKC command on my New Beetle, and I get this:

Version 0.74-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 9600 17 getSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 6.0.2
Culture: hu-HU
Opening serial port com2
Sending wakeup message
Wakeup duration: 1,9999983791244191 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1C0919861AX KOMBI+WEGFAHRS. M73 V26
Software Coding 00142, Workshop Code: 00288
Caught: System.NotImplementedException The method or operation is not implemented.
Unhandled exception: System.NotImplementedException: The method or operation is not implemented.
   at BitFab.KW1281Test.Cluster.MarelliCluster.DumpEeprom(Nullable`1 address, Nullable`1 length, String dumpFileName) in D:\kw1281\Cluster\MarelliCluster.cs:line 18
   at BitFab.KW1281Test.Tester.GetSkc() in D:\kw1281\Tester.cs:line 482
   at BitFab.KW1281Test.Program.Run(String[] args) in D:\kw1281\Program.cs:line 241
   at BitFab.KW1281Test.Program.Main(String[] args) in D:\kw1281\Program.cs:line 26
   
   ReadIdent:
   
   Version 0.74-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 9600 17 ReadIdent
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 6.0.2
Culture: hu-HU
Opening serial port com2
Sending wakeup message
Wakeup duration: 1,9999983791244191 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1C0919861AX KOMBI+WEGFAHRS. M73 V26
Software Coding 00142, Workshop Code: 00288
Sending ReadIdent block
Ident: Ident.-Nr. Wegfahrs.:VWZ5Z0Y1121269 
Sending EndCommunication block

ReadSoftwareVersion:

Version 0.74-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 9600 17 ReadSoftwareVersion
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 6.0.2
Culture: hu-HU
Opening serial port com2
Sending wakeup message
Wakeup duration: 1,9999983791244191 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1C0919861AX KOMBI+WEGFAHRS. M73 V26
Software Coding 00142, Workshop Code: 00288
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
Sending EndCommunication block

Do you have a solution for Get the SKC? The cluster is made by MagnetiMarelli, main chip :Motorola 1F68K

**Comment by gmenounos** [comment]
Looks like I broke something in version 0.72 (I did a lot of internal reorganization). Try version 0.71 for now.

**Comment by fktbnd** [comment]
Thank for your support! This is the result with 0.71:
Version 0.71-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 9600 17 GetSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 6.0.2
Culture: hu-HU
Opening serial port com2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1C0919861AX KOMBI+WEGFAHRS. M73 V26
Software Coding 00142, Workshop Code: 00288
Unsupported cluster software version
Version 0.71-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 9600 17 ReadIdent
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 6.0.2
Culture: hu-HU
Opening serial port com2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1C0919861AX KOMBI+WEGFAHRS. M73 V26
Software Coding 00142, Workshop Code: 00288
Sending ReadIdent block
Ident: Ident.-Nr. Wegfahrs.:VWZ5Z0Y1121269 
Sending EndCommunication block
Version 0.71-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 9600 17 ReadSoftwareVersion
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 6.0.2
Culture: hu-HU
Opening serial port com2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1C0919861AX KOMBI+WEGFAHRS. M73 V26
Software Coding 00142, Workshop Code: 00288
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
Sending EndCommunication block

**Comment by fktbnd** [comment]
Maybe this helps:

Version 0.71-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 9600 17 DumpMarelliMem 3072 1024
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 6.0.2
Culture: hu-HU
Opening serial port com2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1C0919861AX KOMBI+WEGFAHRS. M73 V26
Software Coding 00142, Workshop Code: 00288
Untested cluster version! You may need to disconnect your battery if this fails.
Sending block 0x6C
Writing data to cluster microcontroller
Receiving ACK
Writing memory dump program to cluster microcontroller
Receiving ACK
Receiving memory dump
Saved memory dump to marelli_mem_$0C00.bin
Done
[marelli_mem_$0C00.log](https://github.com/gmenounos/kw1281test/files/8928517/marelli_mem_.0C00.log)

**Comment by gmenounos** [comment]
Well, it looks like you were able to retrieve an EEPROM dump. However, the data in the dump looks a bit different from other Beetle dumps I've worked with. Do you know whether this car is Immobilizer version 2 or 3? If it's version 3, then you should try DumpMarelliMem 14336 2048 and see if that works.

Based on the dump you shared, the SKC _might_ be 29622 or 04120, but I'm not sure.

**Comment by fktbnd** [comment]
Its built in 1998, first gen immo2. I think the cluster was changed by the previus owner, because the date stickers on cluster are younger than the car. I tried 14336 2048 with no luck. I will try the 2 SKC, thanks. Is there a way to get a full dump from the cluster?

**Comment by fktbnd** [comment]
Unfortunately 29622 and 04120 dont work.

**Comment by gmenounos** [comment]
So your SKC is 02067? I can try to incorporate that SKC EEPROM location in a future version of kw1281test but first I'll need to figure out a way to determine whether the SKC is at 0x0202-0x203 or 0x313-0x314. Apparently, both locations are used by Immo2 Beetle clusters. Thanks for alerting me to the 0x0202 SKC location.

Unfortunately, I don't know if it's possible to adjust the cold engine light temperature.

**Comment by fktbnd** [comment]
The adress 0x0202-0x0203 is HEX 13 68 so the skc 04968. Am i wrong with the adresses? Is there a way to get the full eeprom?
