### ISSUE TITLE
Golf 4 AJM - failed to unlock cluster

### ISSUE THREAD

**Issue by jjjjoao** [gmenounos/kw1281test#19]
Hi! I have a 2000 AJM PD Golf 4 with a VDO BOO V22 Cluster with MFA/Half FIS.

I can't seem to read or dump the cluster's EEPROM - Unknown cluster software version.

Here's the log: 

`Opening serial port com5
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0920822C  KOMBI+WEGFAHRS. BOO V22
Software Coding 07144, Workshop Code: 00000
Sending ReadIdent block
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
Cluster did not return software version.
Unknown cluster software version. EEPROM access will likely fail.
Sending Custom "Need Seed/Key?" block
Sending Custom "Seed request" block
Sending Custom "Need Seed/Key?" block
Failed to unlock cluster.
Saving EEPROM dump to Ident.-Nr._WEGFAHRS.**my vin **_$0000_eeprom.bin
Caught: System.ArgumentException Illegal characters in path. (Parameter 'path')

This is using the latest alpha, I've tried both the 0.73 and 0.74 versions as well to no avail. 

EEPROM map seems to fail as it outputs a 2kb file of 0x00s.

Actuator test works.

Am I doing something wrong or is this cluster unsupported?

Cheers. Thank you for your great work!

**Comment by gmenounos** [comment]
Hi João,

Your log doesn't show me what command you were running. Can you try the GetSKC command with version 0.74 and see if that works any better?

Thanks, Greg

**Comment by jjjjoao** [comment]
Hey Greg!
IIRC, I was trying to read the eeprom using the ReadEeprom argument.
Anyway, here's the GetSKC and ReadEeprom command log on 0.74:

`Version 0.74-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM1 10400 17 GetSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 6.0.2
Culture: en-US
Opening serial port COM1
Sending wakeup message
Wakeup duration: 1.999998075259904 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0920822C  KOMBI+WEGFAHRS. BOO V22
Software Coding 07144, Workshop Code: 00000
Sending 0x43 block
Received $FF block: 0x0E 0x0B 0xFF 0x68 0x39 0x33 0x34 0x30 0x5F 0x31 0x30 0x2E 0x33 0x2D 0x03
Received $FF block: 0x0D 0x0D 0xFF 0x63 0x39 0x33 0x34 0x30 0x5F 0x31 0x30 0x2E 0x31 0x03
h9340_10.3-
c9340_10.1
Sending Login block
Sending Custom $08 $15 block
Sending ReadIdent block
Saving EEPROM dump to Ident.-Nr._WEGFAHRS.XVWZ6Z0X1187515X_$0000_eeprom.bin
Sending ReadEeprom block (Address: $0000, Count: $10)
Received "Read EEPROM Response" block: 08 15 2D 00 2D 00 2D 00 28 70 28 70 28 70 46 69
Saved EEPROM dump to Ident.-Nr._WEGFAHRS.XVWZ6Z0X1187515X_$0000_eeprom.bin
SKC: 07028
Sending EndCommunication block
Version 0.74-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM1 10400 17 DumpEEPROM 0 2048
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 6.0.2
Culture: en-US
Opening serial port COM1
Sending wakeup message
Wakeup duration: 1.999999358419968 seconds
Reading sync byte
Retrying wakeup message...
Wakeup duration: 1.999998716839936 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0920822C  KOMBI+WEGFAHRS. BOO V22
Software Coding 07144, Workshop Code: 00000
Sending ReadIdent block
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
Cluster did not return software version.
Unknown cluster software version. EEPROM access will likely fail.
Sending Custom "Need Seed/Key?" block
Sending Custom "Seed request" block
Sending Custom "Need Seed/Key?" block
Failed to unlock cluster.
Saving EEPROM dump to Ident.-Nr._WEGFAHRS.VWZ6Z0X1187515 _$0000_eeprom.bin
Caught: System.ArgumentException Illegal characters in path. (Parameter 'path')
Unhandled exception: System.ArgumentException: Illegal characters in path. (Parameter 'path')
   at System.IO.Path.GetFullPath(String )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.File.Create(String , Int32 , FileOptions )
   at BitFab.KW1281Test.Cluster.VdoCluster.DumpEeprom(UInt16 startAddr, UInt16 length, Byte maxReadLength, String fileName) in C:\Users\gmeno\src\kw1281test\Cluster\VdoCluster.cs:line 688
   at BitFab.KW1281Test.Cluster.VdoCluster.DumpEeprom(Nullable`1 optionalAddress, Nullable`1 optionalLength, String optionalFileName) in C:\Users\gmeno\src\kw1281test\Cluster\VdoCluster.cs:line 45
   at BitFab.KW1281Test.Tester.DumpClusterEeprom(UInt16 startAddress, UInt16 length, String filename) in C:\Users\gmeno\src\kw1281test\Tester.cs:line 691
   at BitFab.KW1281Test.Tester.DumpEeprom(UInt32 address, UInt32 length, String filename) in C:\Users\gmeno\src\kw1281test\Tester.cs:line 363
   at BitFab.KW1281Test.Program.Run(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 298
   at BitFab.KW1281Test.Program.Main(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 26`

**Comment by jjjjoao** [comment]
Also, it might be important to note that I'm using an el cheapo VAG-KKL cable with a CH340 chip.

**Comment by gmenounos** [comment]
It looks like the GetSKC command worked. It says that your SKC is 07028. Have you checked if that is correct?

However, it looks like the DumpEeprom command has a bug, so I'll work on a fix for that. Thanks for reporting it.
