### ISSUE TITLE
Unable to determine SKC Audi A6 C5 1.9tdi 2004

### ISSUE THREAD

**Issue by Gytazas** [gmenounos/kw1281test#33]
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/10823787/KW1281Test.log)
Hi. For some reason I could not get my SKC. Any ideas what to do next?
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/10823793/KW1281Test.log)

**Comment by gmenounos** [comment]
This is a cluster that I haven't seen before, so I don't know how to unlock it. You'll need to use something else like VagTacho to get the SKC. Sorry.

**Comment by gmenounos** [comment]
I recently added support for some Audi clusters similar to yours. Can you try the GetSKC command again with the latest version?
https://github.com/gmenounos/kw1281test/releases/tag/v0.97-beta

**Comment by kellerman** [comment]
Hello @gmenounos . Thank you for your great work and great effort, which I noticed only recently. I'm open to contributions and help.

I work with these clusters a lot and have pretty much every VDO 4B0920XXXX and 8D0920XXXX dump. 

It is important to mention that some of the A6 C5 (4B0) clusters use non-encrypted and encrypted eeproms. For example 935, 933 and 981's are encrypted and use a newer MCU, and 932 and 936 (and some which I don't remember) are not. As I remember there are 16 cryptomasks which are randomly used in those newer clusters, which I have somewhere in my Nextcloud.
A4 B5 (8D0) are all unencrypted.

I recently tried to read eeproms with your tool from two encrypted clusters - 4B0920933N and 4B0920935D. With the 933N the program was unable to connect (but the cluster was 'ticking twice'). With 935D it was able to connect and view software info, but the read eeprom data was all zeros. I used 0.99 version. Oh yeah, I tried both FTDI and CH340 cables - same results.

OP's 981J is a crypted UK version dump. I have those and can test and reply.

It is also great to hear about [the improved Linux support](https://github.com/gmenounos/kw1281test/pull/73). Waiting for this to merge and test, because I have to use Windows VMs to read these eeproms.
:+1:

**Comment by gmenounos** [comment]
Sorry for the really late reply. It's been a busy few weeks.

@kellerman I'm interested in any information you have about these clusters. You can contact me [here](https://bitfab.com/Contact) if you don't want to post anything publicly.

I'll try to get to the Linux support soon. My test environment is an old Windows laptop so I need to set up dual-boot or a VM to be able to test any Linux-specific changes. I've also got a few Raspberry Pi boards around so maybe I can test with one of those.

**Comment by kellerman** [comment]
No problem, I have been busy as well.
Great work you are doing here! I can't tell about the k-line comms specifics, but I can provide dumps and information about the software/hardware of the cluster.

**Comment by Gytazas** [comment]
Hi. Sorry for late reply. I have tried again GetSKC with your other versions but unfortunately couldn’t get it.

![Image](https://github.com/user-attachments/assets/45cded34-a00e-4c6d-8d16-189689e371d4)

**Comment by DiagProf** [comment]
I have the same problem. The cluster is not in the car either; it is on the desk. It is brand new and has never been installed in a vehicle. I can gladly try something if there is anything you want me to test.

Version 1.0.1 (https://github.com/gmenounos/kw1281test/releases)
Command Line: kw1281test COM9 10400 17 getskc
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 10.0.2
Culture: de-DE
Opening Generic serial port COM9
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 4B0920935F  KOMBI+WEGFAHRS. VDO D14
Software Coding 01183, Workshop Code: 00000
Cluster is Audi C5
Sending custom login block
Sending custom login block
Received block: D1 0A 49 00 73 00 11 01 01 F0
Sending login request
Received block: D1 04 06 D3
Succeeded
Dumping EEPROM to AudiC5.bin
Received block: D1 05 15 22 E3
Caught: System.InvalidOperationException Expected block of type $72
Unhandled exception: System.InvalidOperationException: Expected block of type $72
   at BitFab.KW1281Test.Cluster.AudiC5Cluster.ReadEepromByAddress(UInt32 addr, Byte readLength) in C:\Users\a\source\repos\kw1281test\Cluster\AudiC5Cluster.cs:line 168
   at BitFab.KW1281Test.Cluster.AudiC5Cluster.DumpEeprom(UInt32 startAddr, UInt32 length, Byte maxReadLength, String fileName) in C:\Users\a\source\repos\kw1281test\Cluster\AudiC5Cluster.cs:line 129
   at BitFab.KW1281Test.Cluster.AudiC5Cluster.DumpEeprom(Nullable`1 address, Nullable`1 length, String dumpFileName) in C:\Users\a\source\repos\kw1281test\Cluster\AudiC5Cluster.cs:line 113
   at BitFab.KW1281Test.Tester.GetSkc() in C:\Users\a\source\repos\kw1281test\Tester.cs:line 628
   at BitFab.KW1281Test.Program.Run(String[] args) in C:\Users\a\source\repos\kw1281test\Program.cs:line 292
   at BitFab.KW1281Test.Program.Main(String[] args) in C:\Users\a\source\repos\kw1281test\Program.cs:line 40

**Comment by DiagProf** [comment]
I tried a different tool... it didn't work either, but a bit more was done with S/K , maybe this information will help.

 0xd1 , 0x04 , 0x49 , 0x9c ,
 0xd1 , 0x0a , 0x49 , 0x00 , 0x73 , 0x00 , 0x11 , 0x01 , 0x01 , 0xf0 ,
 0xd1 , 0x0d , 0x53 , 0x9d , 0x77 , 0x31 , 0x30 , 0x73 , 0x65 , 0x72 , 0x69 , 0x65 , 0x0c , 
 0xd1 , 0x05 , 0x15 , 0xfa , 0x3b ,
 0xd1 , 0x0d , 0x53 , 0x9d , 0x76 , 0x64 , 0x6f , 0x6b , 0x6f , 0x6d , 0x62 , 0x69 , 0x0d , 
 0xd1 , 0x05 , 0x15 , 0xfa , 0x3b ,
 0xd1 , 0x0d , 0x53 , 0x9d , 0x77 , 0x31 , 0x30 , 0x6b , 0x6f , 0x6d , 0x62 , 0x69 , 0x06 , 
 0xd1 , 0x05 , 0x15 , 0xfa , 0x3b ,
 0xd1 , 0x0d , 0x53 , 0x9d , 0x31 , 0x39 , 0x78 , 0x44 , 0x52 , 0x38 , 0x78 , 0x53 , 0x67 , 
 0xd1 , 0x04 , 0x06 , 0xd3 ,
 0xd1 , 0x06 , 0x53 , 0x96 , 0x04 , 0x16 , 
 0xd1 , 0x05 , 0x53 , 0x03 , 0x84 ,
 0xd1 , 0x06 , 0x53 , 0x96 , 0x01 , 0x13 , 
 0xd1 , 0x0e , 0x53 , 0xb9 , 0xa4 , 0xe0 , 0x4b , 0xd5 , 0x3a , 0xf8 , 0x90 , 0x06 , 0x00 , 0xbb ,
 0xd1 , 0x0d , 0x53 , 0x96 , 0x02 , 0x07 , 0xbb , 0xbb , 0xbb , 0xbb , 0xbb , 0xbb , 0x1c , 
 0xd1 , 0x04 , 0x06 , 0xd3 ,

 0xd1 , 0x07 , 0x72 , 0x08 , 0x00 , 0x00 , 0xac , 
 0xd1 , 0x05 , 0x15 , 0x22 , 0xe3 ,
 0xd1 , 0x07 , 0x72 , 0x08 , 0x00 , 0x08 , 0xa4 ,
 0xd1 , 0x05 , 0x15 , 0x22 , 0xe3 ,
 0xd1 , 0x07 , 0x72 , 0x08 , 0x00 , 0x10 , 0xbc , 
 0xd1 , 0x05 , 0x15 , 0x22 , 0xe3 ,
