### ISSUE TITLE
Get SKC on 2004 VW Jetta

### ISSUE THREAD

**Issue by TylerPadrao** [gmenounos/kw1281test#53]
Hi there! I just want to say the KW1281 test you have created is an amazing open source tool! Quick question! I am trying to retrieve my SKC code from my 2004 Jetta but am getting an error. The cable I am using (VAG-COM KKL 409.1 Cable) is being recognized on port COM3. The car ignition is in the on position. I am using both of the following commands on a Windows 11 computer:

kw1281test COM3 9600 17 GetSKC
kw1281test COM3 10400 17 GetSKC

Here is the output along with the error I am receiving (Using 10400 for BAUD):

C:\Users\tjpad\OneDrive\Documents\Tyler's Docs\VW GLI>kw1281test COM3 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.86-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM3 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.22621.0
.NET Version: 8.0.0
Culture: en-US
Opening serial port COM3
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
Caught: System.InvalidOperationException Received block end $20 but expected $03
Unhandled exception: System.InvalidOperationException: Received block end $20 but expected $03
at BitFab.KW1281Test.KW1281Dialog.ReceiveBlock() in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 392
at BitFab.KW1281Test.KW1281Dialog.ReceiveBlocks() in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 351
at BitFab.KW1281Test.KW1281Dialog.Connect() in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 91
at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in C:\Users\gmeno\src\kw1281test\Tester.cs:line 39
at BitFab.KW1281Test.Tester.GetSkc() in C:\Users\gmeno\src\kw1281test\Tester.cs:line 518
at BitFab.KW1281Test.Program.Run(String[]) in C:\Users\gmeno\src\kw1281test\Program.cs:line 253
at BitFab.KW1281Test.Program.Main(String[]) in C:\Users\gmeno\src\kw1281test\Program.cs:line 29

Here is the output along with the error I am receiving (Using 9600 for BAUD):

C:\Users\tjpad\OneDrive\Documents\Tyler's Docs\VW GLI>kw1281test COM3 9600 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.86-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM3 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.22621.0
.NET Version: 8.0.0
Culture: en-US
Opening serial port COM3
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Caught: System.InvalidOperationException Unexpected sync byte: Expected $55, Actual $95
Unhandled exception: System.InvalidOperationException: Unexpected sync byte: Expected $55, Actual $95
at BitFab.KW1281Test.KwpCommon.WakeUp(Byte, Boolean) in C:\Users\gmeno\src\kw1281test\KwpCommon.cs:line 76
at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in C:\Users\gmeno\src\kw1281test\Tester.cs:line 32
at BitFab.KW1281Test.Tester.GetSkc() in C:\Users\gmeno\src\kw1281test\Tester.cs:line 518
at BitFab.KW1281Test.Program.Run(String[]) in C:\Users\gmeno\src\kw1281test\Program.cs:line 253
at BitFab.KW1281Test.Program.Main(String[]) in C:\Users\gmeno\src\kw1281test\Program.cs:line 29

What would be the cause of this error? Any insight is appreciated!

**Comment by TylerPadrao** [comment]
Hey Greg, I used the same command with version 0.85 and I was able to pull the SKC. Seems like the latest version 0.86 is throwing the above error. Just wanted to let you know.

**Comment by gmenounos** [comment]
This issue coincides with kw1281test's upgrade to .NET 8. Every version of .NET adds additional speed improvements, so I suspect that this is timing related. I've been able to reproduce the issue but it happens only sporadically. I believe I have a fix so expect a new version shortly.
