### ISSUE TITLE
Unsupported Cluster - MK1 2000 Audi TT

### ISSUE THREAD

**Issue by PutzPutz** [gmenounos/kw1281test#56]
Hi Greg, 

Some really cool work you have done here.  Any chance you will be able to support my cluster? 

See code below.  

Version 0.87-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM5 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.22621.0
.NET Version: 8.0.0
Culture: en-US
Opening serial port COM5
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 8N1920930B  KOMBI+WEGFAHRS. M73 D23
Software Coding 02244, Workshop Code: 131071
Caught: System.InvalidOperationException Unsupported cluster version.
Unhandled exception: System.InvalidOperationException: Unsupported cluster version.
   at BitFab.KW1281Test.Cluster.MarelliCluster.GetDefaultAddress() in /Users/gmenounos/Library/CloudStorage/OneDrive-Personal/src/kw1281test/Cluster/MarelliCluster.cs:line 38
   at BitFab.KW1281Test.Cluster.MarelliCluster.DumpEeprom(Nullable`1, Nullable`1, String ) in /Users/gmenounos/Library/CloudStorage/OneDrive-Personal/src/kw1281test/Cluster/MarelliCluster.cs:line 18
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/Library/CloudStorage/OneDrive-Personal/src/kw1281test/Tester.cs:line 601
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/Library/CloudStorage/OneDrive-Personal/src/kw1281test/Program.cs:line 253
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/Library/CloudStorage/OneDrive-Personal/src/kw1281test/Program.cs:line 29

**Comment by gmenounos** [comment]
Can you try the following 2 commands and attach the kw1281test.log and any dumps that are produced?

- kw1281test COM5 9600 17 DumpMarelliMem 3072 1024
- kw1281test COM5 9600 17 DumpMarelliMem 14336 2048

**Comment by PutzPutz** [comment]
The first one worked and actually got something to dump.  Second command timed out.  I tried it twice.  


[Take2.txt](https://github.com/gmenounos/kw1281test/files/13881691/Take2.txt)
[marelli_mem_$0C00_Copy.txt](https://github.com/gmenounos/kw1281test/files/13881692/marelli_mem_.0C00_Copy.txt)

**Comment by PutzPutz** [comment]
githum wouldnt let me upload the merelli_mem document as the bin file that it got dumped as.  Is the text file okay?

**Comment by gmenounos** [comment]
Is your SKC 05802?

**Comment by gmenounos** [comment]
You can also email me the bin file. My email address can be found here: https://bitfab.com/Contact

**Comment by PutzPutz** [comment]
Ill try that SKC after work tonight.  I emailed you the bin.

**Comment by PutzPutz** [comment]
That skc did not work.

**Comment by gmenounos** [comment]
I'll add support for your cluster in the next release, but as far as I know the SKC should be correct because I calculated it correctly: https://github.com/gmenounos/kw1281test/issues/50#issuecomment-1770255129

**Comment by PutzPutz** [comment]
okay.  Could you re calculate it one more time?  I have tried the skc a couple times now with no luck.

**Comment by gmenounos** [comment]
Try this new version and see if it calculates the same SKC. You should now be able to use the GetSKC command instead of DumpMarelliMem:

`kw1281test COM5 9600 17 GetSKC`

https://github.com/gmenounos/kw1281test/releases/tag/v0.88-beta

**Comment by PutzPutz** [comment]
It gave me the same SKC (05802).  Any ideas why this code would not be working? Is it possible that it isn't the original instrument cluster? 

![IMG_6064](https://github.com/gmenounos/kw1281test/assets/155828442/98672c47-46c5-440e-8051-46bccf41b89d)

Version 0.88-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM5 10040 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.22621.0
.NET Version: 8.0.0
Culture: en-US
Opening serial port COM5
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 8N1920930B  KOMBI+WEGFAHRS. M73 D23
Software Coding 02244, Workshop Code: 131071
entryH: 0x02, regBlockH: 0x08, count: 0x0400
Sending block 0x6C
Writing data to cluster microcontroller
Receiving ACK
Writing memory dump program to cluster microcontroller
(Entry: $0200, RegBlock: $0800, Start: $0C00, Count: $0400)
Receiving ACK
Receiving memory dump
Saved memory dump to marelli_mem_$0C00.bin
Done
SKC: 05802

**Comment by gmenounos** [comment]
Can you check the appropriate cluster measuring blocks with VCDS and see if the cluster is locked out?
https://www.ross-tech.com/vag-com/cars/Immo3-measuring-blocks.html

**Comment by elektromouse** [comment]
hello, i have similar problem with mk1 audi tt. 
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/13993943/KW1281Test.log)

i did dump cluster memory with "dumpMirelliMem", should i convert this file to .txt and upload it here?

**Comment by gmenounos** [comment]
Better if you email it to me than converting to .txt
My contact info is here: https://bitfab.com/Contact

**Comment by elektromouse** [comment]
> Better if you email it to me than converting to .txt My contact info is here: https://bitfab.com/Contact

did it. thank you for helping me

**Comment by gmenounos** [comment]
> hello, i have similar problem with mk1 audi tt. [KW1281Test.log](https://github.com/gmenounos/kw1281test/files/13993943/KW1281Test.log)
> 
> i did dump cluster memory with "dumpMirelliMem", should i convert this file to .txt and upload it here?

See if this new release works for your cluster: https://github.com/gmenounos/kw1281test/releases/tag/v0.89-beta

**Comment by elektromouse** [comment]
> > hello, i have similar problem with mk1 audi tt. [KW1281Test.log](https://github.com/gmenounos/kw1281test/files/13993943/KW1281Test.log)
> > i did dump cluster memory with "dumpMirelliMem", should i convert this file to .txt and upload it here?
> 
> See if this new release works for your cluster: https://github.com/gmenounos/kw1281test/releases/tag/v0.89-beta

No luck... and looks like i lost connection with ecu and dash cluster... 
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/13999256/KW1281Test.log)

**Comment by elektromouse** [comment]
did try one more time. Now cluster won't wake up
[KW1281Test2.log](https://github.com/gmenounos/kw1281test/files/14002398/KW1281Test2.log)

**Comment by gmenounos** [comment]
Some of the module wakeup timings were off. Try this new version and see if it works better: https://github.com/gmenounos/kw1281test/releases/tag/v0.90-beta

**Comment by elektromouse** [comment]
Yahoo! i was able to read skc! even with 0.89 version. Will include log in next message if you interested
Will try 0.90 anyway 
Thank you!

**Comment by jbesteele** [comment]
Hi thanks in advance for your great work
I have 2006 Beetle but had to buy new instrument cluster as old one failed. I'm getting the unsupported cluster message. I tried beta 88, 89 and 90 just to check. None of the mem dump commands work for me. They do cause my cluster to make a weird noise and it displays an odd word or message that looks like "ter"
Here's the top few lines from kw1821test: 
ECU: 1C0920501PX KOMBI+WEGFAHRS. M73 V03
Software Coding 15234, Workshop Code: 00000
Unhandled exception: System.InvalidOperationException: Unsupported cluster version.

Is there a way to pull my cluster version? Im stumped
