### ISSUE TITLE
Cannot get sku code from engine ecu VW Polo 9N AZQ

### ISSUE THREAD

**Issue by BurmazDaniel** [gmenounos/kw1281test#57]
Hello! Your tool is amazing but i have a small issue!
I cannot get the skc pin out of my ecu. It is a Siemens SIMOS3 3PE. 
Other commands like ClearFaultCodes, ReadIdent, ReadFaultCodes work but everything else related to eeprom read/write gives this error:
```
Version 0.92-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM2 10400 1 GetSKC
OSVersion: Microsoft Windows NT 10.0.22631.0
.NET Version: 8.0.0
Culture: ro-RO
Opening serial port COM2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 03E906033L  1.2l/4V SIMOS3  00HS4726
Software Coding 00071, Workshop Code: 00788
Sending EndCommunication block
Reading sync byte
Keyword Lsb $EF
Keyword Msb $8F
Protocol is KW 2031 (8N1)
Sent: 82 01 F1 10 89 0D (startDiagnosticSession)
Caught: System.TimeoutException The operation has timed out.
Unhandled exception: System.TimeoutException: The operation has timed out.
   at System.IO.Ports.SerialPort.ReadByte()
   at BitFab.KW1281Test.Interface.GenericInterface.ReadByte() in /Users/gmenounos/src/kw1281test/Interface/GenericInterface.cs:line 34
   at BitFab.KW1281Test.KwpCommon.ReadByte() in /Users/gmenounos/src/kw1281test/KwpCommon.cs:line 130
   at BitFab.KW1281Test.KW2000Dialog.ReceiveMessage() in /Users/gmenounos/src/kw1281test/Kwp2000/KW2000Dialog.cs:line 199
   at BitFab.KW1281Test.KW2000Dialog.SendReceive(DiagnosticService, Byte[], Boolean ) in /Users/gmenounos/src/kw1281test/Kwp2000/KW2000Dialog.cs:line 122
   at BitFab.KW1281Test.EDC15.Edc15VM.ReadWriteEeprom(String, List`1 ) in /Users/gmenounos/src/kw1281test/EDC15/Edc15VM.cs:line 21
   at BitFab.KW1281Test.Tester.ReadWriteEdc15Eeprom(String , List`1 ) in /Users/gmenounos/src/kw1281test/Tester.cs:line 367
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Tester.cs:line 636
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 31
```
I am trying to adapt my new used engine ecu with my old broken one. I have the old engine ecu skc from my instrument cluster. I am using a ch340 vag kkl cable (the blue one). 
I tried using 9600 baudrate, changing COM number, used another pc, used ubuntu, used older versions of this tool but nothing works.
I am honestly so sad because i spent about a month trying and trying and nothing seems to work.
Thank you!

**Comment by gmenounos** [comment]
Sorry, I have no way to support this ECU. I only have access to VW TDI ECUs.
