### ISSUE TITLE
2004 mk4 golf didnt return skc

### ISSUE THREAD

**Issue by fuhrmann07** [gmenounos/kw1281test#64]
running the latest version 0.93
amazon vag kkl cable on port 3

C:\Users\mark\Desktop>.\kw1281test.exe COM3 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.93.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM3 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.18363.0
.NET Version: 8.0.0
Culture: en-CA
Opening serial port COM3
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
Caught: System.InvalidOperationException Received block end $20 but expected $03. Block bytes:  0F F0 0F 01 F6 B1 4A 30 39 32 30 38 30 37 45 20
Unhandled exception: System.InvalidOperationException: Received block end $20 but expected $03. Block bytes:  0F F0 0F 01 F6 B1 4A 30 39 32 30 38 30 37 45 20
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlock() in /Users/gmenounos/src/kw1281test/KW1281Dialog.cs:line 392
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlocks() in /Users/gmenounos/src/kw1281test/KW1281Dialog.cs:line 351
   at BitFab.KW1281Test.KW1281Dialog.Connect() in /Users/gmenounos/src/kw1281test/KW1281Dialog.cs:line 91
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in /Users/gmenounos/src/kw1281test/Tester.cs:line 39

What did I do wrong!  Thx

**Comment by fuhrmann07** [comment]
got this tonight..

C:\Users\mark\Desktop>.\kw1281test.exe COM3 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.93.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM3 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 8.0.0
Culture: en-CA
Opening serial port COM3
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0920807E  KOMBI+WEGFAHRSP VDO V02
Software Coding 15332, Workshop Code: 00000
Sending ReadIdent block
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
00: VWK503LL $00 $09
01: $58 $20
02: $13 $0B $02 $0D $35 $04
03: VW/Sk LL ROM-Maske
Sending Custom "Unlock partial EEPROM read" block
Unlock code for software version 'VWK503LL 09.00' is 3E 35 3D 3A
Sending Custom "Need Seed/Key?" block
Sending Custom "Seed request" block
Block:  3A 46 7B CB 76 47 10 B2 01 00
Sending Custom "Key response" block
Sending Custom "Need Seed/Key?" block
Cluster is unlocked for ROM/EEPROM access.
Saving EEPROM dump to 9BWFR21J644018591_____VWZ7Z0C7083262_$0090_eeprom.bin
Sending ReadEeprom block (Address: $0090, Count: $10)
Caught: System.TimeoutException The operation has timed out.
Unhandled exception: System.TimeoutException: The operation has timed out.
   at System.IO.Ports.SerialPort.ReadByte()
   at BitFab.KW1281Test.KwpCommon.ReadComplement(Byte) in /Users/gmenounos/src/kw1281test/KwpCommon.cs:line 140
   at BitFab.KW1281Test.KW1281Dialog.SendBlock(List`1) in /Users/gmenounos/src/kw1281test/KW1281Dialog.cs:line 338
   at BitFab.KW1281Test.KW1281Dialog.ReadEeprom(UInt16, Byte) in /Users/gmenounos/src/kw1281test/KW1281Dialog.cs:line 142
   at BitFab.KW1281Test.Cluster.VdoCluster.DumpEeprom(UInt16, UInt16, Byte, String) in /Users/gmenounos/src/kw1281test/Cluster/VdoCluster.cs:line 715
   at BitFab.KW1281Test.Cluster.VdoCluster.DumpEeprom(Nullable`1, Nullable`1, String ) in /Users/gmenounos/src/kw1281test/Cluster/VdoCluster.cs:line 45
   at BitFab.KW1281Test.Tester.DumpClusterEeprom(UInt16, UInt16, String ) in /Users/gmenounos/src/kw1281test/Tester.cs:line 879
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Tester.cs:line 546
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 31

**Comment by gmenounos** [comment]
I'd recommend trying a few more times. Looks like it almost worked the 2nd time.

**Comment by fuhrmann07** [comment]
I got it, I was messing up the command prompt as I was copying in the line from the instructions...  Thank you for creating this...
tested it in vcds and all good!

I would like to swap a tuned ecu that i don't have pin for, is there a command that can pull the skc from the ecu like i believe tacho can?

complete nooby here!

**Comment by gmenounos** [comment]
The BEW ECU is an EDC16 and kw1281test only supports EDC15 right now. I'm going to close this issue. You should start a separate issue to request EDC16 support.
