### ISSUE TITLE
WriteEepromResponseBlock body does not match WriteEepromBlock

### ISSUE THREAD

**Issue by biohazark** [gmenounos/kw1281test#8]
Hi,
I got this error while programming my CCM :

Sending WriteEeprom block (Address: $21B4, Values: $F4 
Received "Write EEPROM Response" block: 01 20 B4 F4
WriteEepromResponseBlock body does not match WriteEepromBlock

I expect the value F4 was written to the wrong address (20 B4 instead of 21 B4), so maybe some data were unintentionally overwrite, and data loss...

When I started using of your program I also got an error dumping CCM module : 

Sending ReadEeprom block (Address: $0005D0, Count: $08)
Caught: System.InvalidOperationException Received block end $83 but expected $03
Unhandled exception: System.InvalidOperationException: Received block end $83 but expected $03
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlock() in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 474
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlocks() in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 433
   at BitFab.KW1281Test.KW1281Dialog.ReadCcmRom(Byte seg, Byte msb, Byte lsb, Byte count) in C:\Users\gmeno\src\kw1281test\KW1281Dialog.cs:line 178
   at BitFab.KW1281Test.Program.DumpCcmRom(IKW1281Dialog kwp1281) in C:\Users\gmeno\src\kw1281test\Program.cs:line 463
   at BitFab.KW1281Test.Program.Run(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 191
   at BitFab.KW1281Test.Program.Main(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 26

**Comment by biohazark** [comment]
Issue also occured for these addresses:

Sending WriteEeprom block (Address: $31B4, Values: $FC 
Received "Write EEPROM Response" block: 01 30 B4 FC
WriteEepromResponseBlock body does not match WriteEepromBlock

Sending WriteEeprom block (Address: $41B4, Values: $F4 
Received "Write EEPROM Response" block: 01 40 B4 F4
WriteEepromResponseBlock body does not match WriteEepromBlock

Sending WriteEeprom block (Address: $51B4, Values: $FC 
Received "Write EEPROM Response" block: 01 50 B4 FC
WriteEepromResponseBlock body does not match WriteEepromBlock

Sending WriteEeprom block (Address: $41B3, Values: $57 
Received "Write EEPROM Response" block: 01 40 B3 57
WriteEepromResponseBlock body does not match WriteEepromBlock

Sending WriteEeprom block (Address: $51B3, Values: $57 
Received "Write EEPROM Response" block: 01 50 B3 57
WriteEepromResponseBlock body does not match WriteEepromBlock

A quick look on this problem reveals that 8th bit (xxxxxxx1xxxxxxxx) of the adsress was replaced from 1 to 0. I didn't get any troubles for other addresses were 8th bit was 0 (maybe it's a coincidence, maybe not...) hope you could fix this in order to reset my original values of my CCM

**Comment by gmenounos** [comment]
What version of kw1281test are you running? Can you either attach the log (kw1281test.log) to this issue or email it to me?

**Comment by biohazark** [comment]
I just realized I stupidly didn't mention the version and the OS, you were faster than me !
So I used kw1281test_0.62-beta_Win10.zip under Windows 7 build 7601 x64

Here is the log file, but it's a little bit long...

[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/7003587/KW1281Test.log)

thx

**Comment by gmenounos** [comment]
Well first of all, the DumpCcmRom command doesn't work. I added it a while ago for testing but never got it to work correctly. I'm going to remove it until I can get it working. But in case you were using that command to try to back up your EEPROM before changing it, there's a different command for that: DumpEeprom
To completely back up everything, you need to back up the CCM and all window motors. Each has 512 bytes of EEPROM but each has a different starting address. Here are the 5 commands to dump the CCM and all 4 window motors. If you have a 2-door car, skip the last 2 commands.

.\kw1281test.exe COM3 9600 46 DumpEeprom  4096 512
.\kw1281test.exe COM3 9600 46 DumpEeprom  8192 512
.\kw1281test.exe COM3 9600 46 DumpEeprom 12288 512
.\kw1281test.exe COM3 9600 46 DumpEeprom 16384 512
.\kw1281test.exe COM3 9600 46 DumpEeprom 20480 512

The second thing is that I think you may have some noise on the K-Line in your car or maybe your cable is not working well for some reason. The reason I think so is because you're getting a few errors like these:

Caught: System.InvalidOperationException Received block end $83 but expected $03
Caught: System.InvalidOperationException Wrote 0x75 to port but echo was 0x55

Normally you shouldn't see errors like those. I would suggest trying a different KKL cable if you have access to one. You also might try disconnecting your ECU and/or cluster or pulling the fuses that power them and see if the errors go away. You might also try disconnecting the battery or just trying again later. Other people have reported errors like yours and then later on everything worked fine with no explanation for why they didn't work the first time.

**Comment by biohazark** [comment]
Same issue with an other KKL Cable, so for following hardware : 

VAG-K + CAN  : FTDI 1911-C (FT232RL) chip
VAG KKL 409.1 : CH340T chip

I also have a HEX-V2 Dual K & CAN cable but it don't use COM port emulation so I don't think it's compatible with your soft.

I don't think that's noise related, cause this is systematic and only for addresses that have a 1 to 8th bit.

I can confirm it has overwritten wrong adresses so I need to retrieve original value for G4 five doors located at 08372, 16564, 12468, 20660, 16563, 20659 of 46 (CCM) module

**Comment by biohazark** [comment]
EDIT3 : 
I suspect a redundancy on these addresses, is that possible ?

ReadEeprom **08628** -> 242
WriteEeprom _08372_ 246 (no error message)
ReadEeprom **08628** -> 246


Log : 

Version 0.62-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM3 9600 46 ReadEeprom 08628
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 5.0.8
Culture: fr-FR
Opening serial port COM3
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0959799AH 4E Zentral-SG Komf. 0001
Software Coding 04097, Workshop Code: 00046
Sending Login block
Sending ReadEeprom block (Address: $21B4, Count: $01)
Received "Read EEPROM Response" block: F2
Address 8628 ($21B4): Value 242 ($F2)
Sending EndCommunication block
Version 0.62-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM3 9600 46 WriteEeprom 08372 246
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 5.0.8
Culture: fr-FR
Opening serial port COM3
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0959799AH 4E Zentral-SG Komf. 0001
Software Coding 04097, Workshop Code: 00046
Sending Login block
Sending WriteEeprom block (Address: $20B4, Values: $F6 
Received "Write EEPROM Response" block: 01 20 B4 F6
Sending EndCommunication block
Version 0.62-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM3 9600 46 ReadEeprom 08628
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 5.0.8
Culture: fr-FR
Opening serial port COM3
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0959799AH 4E Zentral-SG Komf. 0001
Software Coding 04097, Workshop Code: 00046
Sending Login block
Sending ReadEeprom block (Address: $21B4, Count: $01)
Received "Read EEPROM Response" block: F6
Address 8628 ($21B4): Value 246 ($F6)
Sending EndCommunication block

**Comment by WPhH** [comment]
Hi biohazark, did you ever manage to get your windows going via keyfob?  I am running into exactly the same issues, and I can not get it to work..  Thanks for letting me know if you found a solution
