### ISSUE TITLE
TT 8N1920930J  M73 D56 timeout

### ISSUE THREAD

**Issue by danolsn** [gmenounos/kw1281test#85]
I am able to connect to the ECM but I can't pull SKC. I get the sense that these TT clusters vary wildly.

Version 0.99.1-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM3 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 8.0.7
Culture: en-US
Opening serial port COM3
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
Error receiving block: The operation has timed out.
Partial block: $0F $01 $F6 $78 $0F $01 $F6 $38
Read timeout: 8000
Write timeout: 8000
Error receiving blocks: The operation has timed out.
Caught: System.TimeoutException The operation has timed out.
Unhandled exception: System.TimeoutException: The operation has timed out.
   at System.IO.Ports.SerialStream.ReadByte(Int32 _)
   at System.IO.Ports.SerialStream.ReadByte()
   at System.IO.Ports.SerialPort.ReadByte()
   at BitFab.KW1281Test.Interface.GenericInterface.ReadByte() in C:\Users\Daniel\Desktop\AUTO\kw1281test\Interface\GenericInterface.cs:line 34
   at BitFab.KW1281Test.KwpCommon.ReadByte() in C:\Users\Daniel\Desktop\AUTO\kw1281test\KwpCommon.cs:line 130
   at BitFab.KW1281Test.KW1281Dialog.ReadAndAckByte() in C:\Users\Daniel\Desktop\AUTO\kw1281test\KW1281Dialog.cs:line 479
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlock() in C:\Users\Daniel\Desktop\AUTO\kw1281test\KW1281Dialog.cs:line 409
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlocks() in C:\Users\Daniel\Desktop\AUTO\kw1281test\KW1281Dialog.cs:line 360
   at BitFab.KW1281Test.KW1281Dialog.Connect() in C:\Users\Daniel\Desktop\AUTO\kw1281test\KW1281Dialog.cs:line 92
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean evenParityWakeup) in C:\Users\Daniel\Desktop\AUTO\kw1281test\Tester.cs:line 40
   at BitFab.KW1281Test.Tester.GetSkc() in C:\Users\Daniel\Desktop\AUTO\kw1281test\Tester.cs:line 509
   at BitFab.KW1281Test.Program.Run(String[] args) in C:\Users\Daniel\Desktop\AUTO\kw1281test\Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[] args) in C:\Users\Daniel\Desktop\AUTO\kw1281test\Program.cs:line 31

**Comment by gmenounos** [comment]
Did you only try once or do you get consistent timeouts? Can you connect to other modules in the car? What kind of cable are you using?

**Comment by danolsn** [comment]
I tried several times.  I also tried DumpMarelliMem which made the cluster reboot/reset the clock/date.  I was able to connect to the ECM ReadIdent which I found as a suggestion in another thread.  I am using a cheap VIMVIP VAG-COM KKL cable. I have a hex-net that I could try if these interfaces work

**Comment by gmenounos** [comment]
Hex-net isn't compatible with kw1281test. Can VCDS lite connect to the cluster? If it also times out then you may need to disconnect the battery from the car for a minute and then reconnect to reset the cluster. The GetSKC command can leave TT clusters in a bad state sometimes. Also, 9600 is the usual baud rate for TT clusters. Try 9600 after disconnecting/reconnecting the battery.

**Comment by danolsn** [comment]
I am able to connect to the cluster with my cable using VCDS lite.  I will try what you recommend later tonight. I assumed the hex-net would be too "smart" for this use.  I was looking all over the internet for similar situations using your (seriously awesome) project, so I tried many things but I did not think of disconnecting power

**Comment by danolsn** [comment]
I made it a little further after disconnecting the battery for a few minutes

Version 0.99.1-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM3 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 8.0.7
Culture: en-US
Opening serial port COM3
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 8N1920930J  KOMBI+WEGFAHRS. M73 D56
Software Coding 07244, Workshop Code: 00050
entryH: 0x02, regBlockH: 0x08, count: 0x0400
Sending block 0x6C
Writing data to cluster microcontroller
Receiving ACK
Writing memory dump program to cluster microcontroller
(Entry: $0200, RegBlock: $0800, Start: $0C00, Count: $0400)
Receiving ACK
Receiving memory dump
Caught: System.TimeoutException The operation has timed out.
Unhandled exception: System.TimeoutException: The operation has timed out.
   at System.IO.Ports.SerialPort.ReadByte()
   at BitFab.KW1281Test.Interface.GenericInterface.ReadByte() in C:\Users\Daniel\Desktop\AUTO\kw1281test\Interface\GenericInterface.cs:line 34
   at BitFab.KW1281Test.KwpCommon.ReadByte() in C:\Users\Daniel\Desktop\AUTO\kw1281test\KwpCommon.cs:line 130
   at BitFab.KW1281Test.Cluster.MarelliCluster.DumpMem(String filename, UInt16 address, Nullable`1 count) in C:\Users\Daniel\Desktop\AUTO\kw1281test\Cluster\MarelliCluster.cs:line 176
   at BitFab.KW1281Test.Cluster.MarelliCluster.DumpEeprom(Nullable`1 address, Nullable`1 length, String dumpFileName) in C:\Users\Daniel\Desktop\AUTO\kw1281test\Cluster\MarelliCluster.cs:line 21
   at BitFab.KW1281Test.Tester.GetSkc() in C:\Users\Daniel\Desktop\AUTO\kw1281test\Tester.cs:line 619
   at BitFab.KW1281Test.Program.Run(String[] args) in C:\Users\Daniel\Desktop\AUTO\kw1281test\Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[] args) in C:\Users\Daniel\Desktop\AUTO\kw1281test\Program.cs:line 31

**Comment by danolsn** [comment]
I ended up resolving this- My TT cluster has large EEPROM.  8N1920930J


Command Line: kw1281test COM2 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 10.0.7
Culture: en-US
Opening Generic serial port COM2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 8N1920930J  KOMBI+WEGFAHRS. M73 D56
Software Coding 07244, Workshop Code: 00050
entryH: 0x18, regBlockH: 0x20, count: 0x0800
Sending block 0x6C
Writing data to cluster microcontroller
Receiving ACK
Writing memory dump program to cluster microcontroller
(Entry: $1800, RegBlock: $2000, Start: $0C00, Count: $0800)
Receiving ACK
Receiving memory dump
Saved memory dump to marelli_mem_$0C00.bin
Done
SKC: XXXXX
