### ISSUE TITLE
Volkswagen  lupo 3L cluster

### ISSUE THREAD

**Issue by sebas273** [gmenounos/kw1281test#97]
Hi
I’ve been using your kw1281test tool , and I really appreciate its functionality. However, I’ve encountered some issues while trying to retrieve the SKC code from my volkswagen lupo 3L 1.2 tdi, and it seems that the ECU might not be fully supported.

Here’s my configuration:

    Car: VW lupo 3l 1.2 tdi 
    ECU: 6E0920800D KOMBIINSTRUMENT BOO V06   (this is not the original one, but the cluster from the engine running into it) another lupo 3l from the year 2000
    Baud rate: 10400
    Protocol: KW1281

When running the following command:

kw1281test.exe COM4 10400 17 GetSKC

I frequently get a timeout error. The tool also shows the warning: "Unknown software version. Login may fail." and the communication fails with the error: "The operation has timed out."

I’ve verified the connection, used the correct COM port, and set the appropriate baud rate. While the ECU responds, the tool seems unable to recognize the software version, which prevents me from retrieving the SKC.

My request is: Would it be possible to update the kw1281test tool to support this specific ECU or car model? If you need any additional information or logs, feel free to let me know. I’m happy to assist in any way to help improve the tool’s functionality.

Thank you in advance for your time and effort. I look forward to hearing from you.

Best regards,
Sebastian

I tried different cables,  ( a chinese VAG-com 10.6 ) no comport available in windows 7 
And I tried a Ftdi cable blue VAG  K CAN commander 

    ClearFaultCodes
        DelcoVWPremium5SafeCode
        DumpEdc15Eeprom [FILENAME]
            FILENAME = Optional filename
        DumpEeprom START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 0) or hex (e.g. $0)
            LENGTH = Number of bytes in decimal (e.g. 2048) or hex (e.g. $800)
            FILENAME = Optional filename
        DumpMarelliMem START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 3072) or hex (e.g. $C00)
            LENGTH = Number of bytes in decimal (e.g. 1024) or hex (e.g. $400)
            FILENAME = Optional filename
        DumpMem START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 8192) or hex (e.g. $2000)
            LENGTH = Number of bytes in decimal (e.g. 65536) or hex (e.g. $10000
)
            FILENAME = Optional filename
        DumpRam START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 8192) or hex (e.g. $2000)
            LENGTH = Number of bytes in decimal (e.g. 65536) or hex (e.g. $10000
)
            FILENAME = Optional filename
        DumpRBxMem START LENGTH [FILENAME]
            START = Start address in decimal (e.g. 66560) or hex (e.g. $10400)
            LENGTH = Number of bytes in decimal (e.g. 1024) or hex (e.g. $400)
            FILENAME = Optional filename
        FindLogins LOGIN
            LOGIN = Known good login (0-65535)
        GetSKC
        GroupRead GROUP
            GROUP = Group number (0-255)
            (Group 0: Raw controller data)
        LoadEeprom START FILENAME
            START = Start address in decimal (e.g. 0) or hex (e.g. $0)
            FILENAME = Name of file containing binary data to load into EEPROM
        MapEeprom
        ReadFaultCodes
        ReadIdent
        ReadEeprom ADDRESS
            ADDRESS = Address in decimal (e.g. 4361) or hex (e.g. $1109)
        ReadRAM ADDRESS
            ADDRESS = Address in decimal (e.g. 4361) or hex (e.g. $1109)
        ReadROM ADDRESS
            ADDRESS = Address in decimal (e.g. 4361) or hex (e.g. $1109)
        ReadSoftwareVersion
        Reset
        SetSoftwareCoding CODING WORKSHOP
            CODING = Software coding in decimal (e.g. 4361) or hex (e.g. $1109)
            WORKSHOP = Workshop code in decimal (e.g. 4361) or hex (e.g. $1109)
        ToggleRB4Mode
        WriteEdc15Eeprom ADDRESS1 VALUE1 [ADDRESS2 VALUE2 ... ADDRESSn VALUEn]
            ADDRESS = EEPROM address in decimal (0-511) or hex ($00-$1FF)
            VALUE = Value to be stored at address in decimal (0-255) or hex ($00
-$FF)
        WriteEeprom ADDRESS VALUE
            ADDRESS = Address in decimal (e.g. 4361) or hex (e.g. $1109)
            VALUE = Value in decimal (e.g. 138) or hex (e.g. $8A)

C:\Users\eee\Desktop>kw1281test.exe COM4 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.93.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM4 10400 17 GetSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 8.0.0
Culture: nl-NL
Opening serial port COM4
Sending wakeup message
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Caught: System.InvalidOperationException Controller did not wake up.
Unhandled exception: System.InvalidOperationException: Controller did not wake u
p.
   at BitFab.KW1281Test.KwpCommon.WakeUp(Byte, Boolean) in /Users/gmenounos/src/
kw1281test/KwpCommon.cs:line 62
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in /Users/gmenounos/src/k
w1281test/Tester.cs:line 32
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Teste
r.cs:line 519
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test
/Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281tes
t/Program.cs:line 31

C:\Users\eee\Desktop>kw1281test.exe COM4 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.93.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM4 10400 17 GetSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 8.0.0
Culture: nl-NL
Opening serial port COM4
Sending wakeup message
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Caught: System.InvalidOperationException Controller did not wake up.
Unhandled exception: System.InvalidOperationException: Controller did not wake u
p.
   at BitFab.KW1281Test.KwpCommon.WakeUp(Byte, Boolean) in /Users/gmenounos/src/
kw1281test/KwpCommon.cs:line 62
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in /Users/gmenounos/src/k
w1281test/Tester.cs:line 32
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Teste
r.cs:line 519
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test
/Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281tes
t/Program.cs:line 31

C:\Users\eee\Desktop>kw1281test.exe COM4 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.93.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM4 10400 17 GetSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 8.0.0
Culture: nl-NL
Opening serial port COM4
Caught: System.IO.FileNotFoundException Could not find file 'COM4'.
Unhandled exception: System.IO.FileNotFoundException: Could not find file 'COM4'
.
File name: 'COM4'
   at System.IO.Ports.SerialStream..ctor(String, Int32, Parity, Int32, StopBits,
 Int32, Int32, Handshake, Boolean, Boolean, Boolean, Byte)
   at System.IO.Ports.SerialPort.Open()
   at BitFab.KW1281Test.Interface.GenericInterface..ctor(String, Int32) in /User
s/gmenounos/src/kw1281test/Interface/GenericInterface.cs:line 23
   at BitFab.KW1281Test.Program.OpenPort(String, Int32) in /Users/gmenounos/src/
kw1281test/Program.cs:line 500
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test
/Program.cs:line 259
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281tes
t/Program.cs:line 31

C:\Users\eee\Desktop>kw1281test.exe COM1 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.93.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM1 10400 17 GetSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 8.0.0
Culture: nl-NL
Opening serial port COM1
Caught: System.IO.FileNotFoundException Could not find file 'COM1'.
Unhandled exception: System.IO.FileNotFoundException: Could not find file 'COM1'
.
File name: 'COM1'
   at System.IO.Ports.SerialStream..ctor(String, Int32, Parity, Int32, StopBits,
 Int32, Int32, Handshake, Boolean, Boolean, Boolean, Byte)
   at System.IO.Ports.SerialPort.Open()
   at BitFab.KW1281Test.Interface.GenericInterface..ctor(String, Int32) in /User
s/gmenounos/src/kw1281test/Interface/GenericInterface.cs:line 23
   at BitFab.KW1281Test.Program.OpenPort(String, Int32) in /Users/gmenounos/src/
kw1281test/Program.cs:line 500
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test
/Program.cs:line 259
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281tes
t/Program.cs:line 31

C:\Users\eee\Desktop>kw1281test.exe CO2 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.93.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: CO2 10400 17 GetSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 8.0.0
Culture: nl-NL
Opening serial port CO2
Caught: System.ArgumentException The given port name (CO2) does not resolve to a
 valid serial port. (Parameter 'portName')
Unhandled exception: System.ArgumentException: The given port name (CO2) does no
t resolve to a valid serial port. (Parameter 'portName')
   at System.IO.Ports.SerialStream..ctor(String, Int32, Parity, Int32, StopBits,
 Int32, Int32, Handshake, Boolean, Boolean, Boolean, Byte)
   at System.IO.Ports.SerialPort.Open()
   at BitFab.KW1281Test.Interface.GenericInterface..ctor(String, Int32) in /User
s/gmenounos/src/kw1281test/Interface/GenericInterface.cs:line 23
   at BitFab.KW1281Test.Program.OpenPort(String, Int32) in /Users/gmenounos/src/
kw1281test/Program.cs:line 500
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test
/Program.cs:line 259
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281tes
t/Program.cs:line 31

C:\Users\eee\Desktop>kw1281test.exe COm4 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.93.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COm4 10400 17 GetSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 8.0.0
Culture: nl-NL
Opening serial port COm4
Sending wakeup message
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 6E0920800D  KOMBIINSTRUMENT BOO V06
Software Coding 00134, Workshop Code: 49689
Sending 0x43 block
Received $FF block: 0x0D 0x0B 0xFF 0x76 0x39 0x31 0x31 0x39 0x5F 0x30 0x34 0x2E
0x31 0x03
v9119_04.1
Warning: Unknown software version. Login may fail.
Sending Login block
Caught: System.TimeoutException The operation has timed out.
Unhandled exception: System.TimeoutException: The operation has timed out.
   at System.IO.Ports.SerialStream.ReadByte(Int32)
   at System.IO.Ports.SerialStream.ReadByte()
   at System.IO.Ports.SerialPort.ReadByte()
   at BitFab.KW1281Test.Interface.GenericInterface.ReadByte() in /Users/gmenouno
s/src/kw1281test/Interface/GenericInterface.cs:line 34
   at BitFab.KW1281Test.KwpCommon.ReadByte() in /Users/gmenounos/src/kw1281test/
KwpCommon.cs:line 130
   at BitFab.KW1281Test.KW1281Dialog.ReadAndAckByte() in /Users/gmenounos/src/kw
1281test/KW1281Dialog.cs:line 442
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlock() in /Users/gmenounos/src/kw12
81test/KW1281Dialog.cs:line 373
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlocks() in /Users/gmenounos/src/kw1
281test/KW1281Dialog.cs:line 351
   at BitFab.KW1281Test.KW1281Dialog.Login(UInt16, Int32) in /Users/gmenounos/sr
c/kw1281test/KW1281Dialog.cs:line 108
   at BitFab.KW1281Test.Cluster.MotometerBOOCluster.UnlockForEepromReadWrite() i
n /Users/gmenounos/src/kw1281test/Cluster/MotometerBOOCluster.cs:line 20
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Teste
r.cs:line 619
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test
/Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281tes
t/Program.cs:line 31

C:\Users\eee\Desktop>kw1281test.exe COm4 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.93.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COm4 10400 17 GetSKC
OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
.NET Version: 8.0.0
Culture: nl-NL
Opening serial port COm4
Sending wakeup message
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 6E0920800D  KOMBIINSTRUMENT BOO V06
Software Coding 00134, Workshop Code: 49689
Sending 0x43 block
Received $FF block: 0x0D 0x0B 0xFF 0x76 0x39 0x31 0x31 0x39 0x5F 0x30 0x34 0x2E
0x31 0x03
v9119_04.1
Warning: Unknown software version. Login may fail.
Sending Login block
Caught: System.TimeoutException The operation has timed out.
Unhandled exception: System.TimeoutException: The operation has timed out.
   at System.IO.Ports.SerialStream.ReadByte(Int32)
   at System.IO.Ports.SerialStream.ReadByte()
   at System.IO.Ports.SerialPort.ReadByte()
   at BitFab.KW1281Test.Interface.GenericInterface.ReadByte() in /Users/gmenouno
s/src/kw1281test/Interface/GenericInterface.cs:line 34
   at BitFab.KW1281Test.KwpCommon.ReadByte() in /Users/gmenounos/src/kw1281test/
KwpCommon.cs:line 130
   at BitFab.KW1281Test.KW1281Dialog.ReadAndAckByte() in /Users/gmenounos/src/kw
1281test/KW1281Dialog.cs:line 442
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlock() in /Users/gmenounos/src/kw12
81test/KW1281Dialog.cs:line 373
   at BitFab.KW1281Test.KW1281Dialog.ReceiveBlocks() in /Users/gmenounos/src/kw1
281test/KW1281Dialog.cs:line 351
   at BitFab.KW1281Test.KW1281Dialog.Login(UInt16, Int32) in /Users/gmenounos/sr
c/kw1281test/KW1281Dialog.cs:line 108
   at BitFab.KW1281Test.Cluster.MotometerBOOCluster.UnlockForEepromReadWrite() i
n /Users/gmenounos/src/kw1281test/Cluster/MotometerBOOCluster.cs:line 20
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Teste
r.cs:line 619
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test
/Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281tes
t/Program.cs:line 31

**Comment by gmenounos** [comment]
It looks like you're running on Windows 7. Any chance you could try this in .NET 10 or 11? kw1281test uses .NET 8, which is no longer supported on Windows versions below 10.

**Comment by sebas273** [comment]
Thank you for your interesting work and quick response! I’m using an old Eee PC since basic VAG-COM only runs on Windows. I will try to dual-boot a Linux version and use your application there. It has an FTDI chip, so that should work. I’ll let you know how it goes. I also used VAG EEPROM Programmer to read out the dash unit, but I got the same message something like unknown software version. I know that in this car everything is different. I hope this doesn't give a problem in linux with your app?
